# Generated by Django 6.1 on 2026-08-16 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Google Email')),
                ('full_name', models.CharField(blank=True, max_length=150, verbose_name='Full Name')),
                ('phone_number', models.CharField(blank=True, max_length=50, verbose_name='WhatsApp / Phone Number')),
                ('region', models.CharField(blank=True, choices=[('san_francisco', 'San Francisco'), ('peninsula', 'Peninsula (San Mateo, Burlingame, Redwood City, Palo Alto, Menlo Park)'), ('south_bay', 'South Bay / Silicon Valley (San Jose, Santa Clara, Sunnyvale, Mountain View)'), ('east_bay', 'East Bay (Oakland, Berkeley, Fremont, Dublin, Pleasanton)'), ('north_bay', 'North Bay (Marin, Sonoma, Napa, Sausalito)'), ('santa_cruz', 'Santa Cruz & South Coast'), ('other', 'Other / Outside Bay Area')], default='', max_length=50, verbose_name='Bay Area Region')),
                ('city', models.CharField(blank=True, help_text='e.g., Sunnyvale, Mission SF, Berkeley Hills', max_length=100, verbose_name='City / Neighborhood')),
                ('family_info', models.CharField(blank=True, help_text='e.g., Kids (ages 3 & 7), Expecting, No kids', max_length=200, verbose_name='Family & Kids Details')),
                ('interests', models.CharField(blank=True, help_text='Comma-separated or selected event interests', max_length=255, verbose_name='Event Interests')),
                ('bio', models.TextField(blank=True, help_text='A few words about you, where you are originally from, hobbies, etc.', verbose_name='About Me / Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Member Profile',
                'verbose_name_plural': 'Member Profiles',
                'ordering': ['full_name', 'email'],
            },
        ),
    ]
