# Generated by Django 6.1 on 2026-08-16 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Organizer / Admin'),
        ),
    ]
