# Generated by Django 6.1 on 2026-08-17 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_memberprofile_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Full Name')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='Google / Gmail Address')),
                ('phone_number', models.CharField(max_length=50, verbose_name='WhatsApp / Phone Number')),
                ('region', models.CharField(blank=True, choices=[('san_francisco', 'San Francisco'), ('peninsula', 'Peninsula (San Mateo, Burlingame, Redwood City, Palo Alto, Menlo Park)'), ('south_bay', 'South Bay / Silicon Valley (San Jose, Santa Clara, Sunnyvale, Mountain View)'), ('east_bay', 'East Bay (Oakland, Berkeley, Fremont, Dublin, Pleasanton)'), ('north_bay', 'North Bay (Marin, Sonoma, Napa, Sausalito)'), ('santa_cruz', 'Santa Cruz & South Coast'), ('other', 'Other / Outside Bay Area')], default='', max_length=50, verbose_name='Bay Area Region')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City / Neighborhood')),
                ('referral_source', models.TextField(blank=True, verbose_name='Referral Source / How did you hear about MiniMexitas?')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Declined')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('reviewed_by', models.CharField(blank=True, max_length=150, verbose_name='Reviewed By')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed At')),
                ('review_notes', models.TextField(blank=True, verbose_name='Internal Review Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Membership Request',
                'verbose_name_plural': 'Membership Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
