# Generated by Django 6.1 on 2026-08-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0003_membershiprequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submitted', 'Request Submitted'), ('approved', 'Request Approved'), ('rejected', 'Request Rejected'), ('direct_added', 'Member Added Directly'), ('deleted', 'Member Deleted')], db_index=True, max_length=30, verbose_name='Action')),
                ('target_email', models.EmailField(db_index=True, max_length=254, verbose_name='Target Member Email')),
                ('target_name', models.CharField(blank=True, max_length=150, verbose_name='Target Member Name')),
                ('actor_name', models.CharField(blank=True, max_length=150, verbose_name='Performed By (Name)')),
                ('actor_email', models.CharField(blank=True, max_length=150, verbose_name='Performed By (Email)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes / Justification')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Timestamp')),
            ],
            options={
                'verbose_name': 'Membership Audit Log',
                'verbose_name_plural': 'Membership Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
