# Generated by Django 6.1 on 2026-08-18 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0004_membershipauditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunitySurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Survey Question / Title')),
                ('description', models.TextField(blank=True, verbose_name='Context & Details')),
                ('category', models.CharField(choices=[('event', 'Event & Meetup'), ('food', 'Food & Culinary'), ('community', 'Community Initiative'), ('general', 'General Question')], default='event', max_length=30, verbose_name='Category')),
                ('is_multiple_choice', models.BooleanField(default=False, verbose_name='Allow Multiple Choices')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active for Voting')),
                ('created_by', models.CharField(blank=True, max_length=150, verbose_name='Created By (Admin Name)')),
                ('created_by_email', models.EmailField(blank=True, max_length=254, verbose_name='Created By (Admin Email)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Community Survey',
                'verbose_name_plural': 'Community Surveys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='membershipauditlog',
            name='action',
            field=models.CharField(choices=[('submitted', 'Request Submitted'), ('approved', 'Request Approved'), ('rejected', 'Request Rejected'), ('direct_added', 'Member Added Directly'), ('deleted', 'Member Deleted'), ('survey_created', 'Survey Created'), ('survey_closed', 'Survey Closed/Reopened'), ('survey_deleted', 'Survey Deleted')], db_index=True, max_length=30, verbose_name='Action'),
        ),
        migrations.CreateModel(
            name='SurveyOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Option Text')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='recommendations.communitysurvey')),
            ],
            options={
                'verbose_name': 'Survey Option',
                'verbose_name_plural': 'Survey Options',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SurveyVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_email', models.EmailField(db_index=True, max_length=254, verbose_name='Voter Email')),
                ('voter_name', models.CharField(max_length=150, verbose_name='Voter Name')),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='recommendations.surveyoption')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='recommendations.communitysurvey')),
            ],
            options={
                'verbose_name': 'Survey Vote',
                'verbose_name_plural': 'Survey Votes',
                'ordering': ['-voted_at'],
                'unique_together': {('survey', 'option', 'voter_email')},
            },
        ),
    ]
