# Generated by Django 6.1 on 2026-08-18 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0005_communitysurvey_alter_membershipauditlog_action_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityEventBroadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Event ID')),
                ('event_title', models.CharField(max_length=255, verbose_name='Event Title')),
                ('broadcast_by', models.CharField(max_length=150, verbose_name='Broadcasted By (Admin Name)')),
                ('broadcast_by_email', models.EmailField(max_length=254, verbose_name='Broadcasted By (Admin Email)')),
                ('recipient_count', models.PositiveIntegerField(default=0, verbose_name='Recipients Count')),
                ('broadcast_at', models.DateTimeField(auto_now=True, verbose_name='Last Broadcasted At')),
            ],
            options={
                'verbose_name': 'Event Broadcast',
                'verbose_name_plural': 'Event Broadcasts',
                'ordering': ['-broadcast_at'],
            },
        ),
        migrations.AlterField(
            model_name='membershipauditlog',
            name='action',
            field=models.CharField(choices=[('submitted', 'Request Submitted'), ('approved', 'Request Approved'), ('rejected', 'Request Rejected'), ('direct_added', 'Member Added Directly'), ('deleted', 'Member Deleted'), ('survey_created', 'Survey Created'), ('survey_closed', 'Survey Closed/Reopened'), ('survey_deleted', 'Survey Deleted'), ('event_broadcast', 'Event Notification Broadcast')], db_index=True, max_length=30, verbose_name='Action'),
        ),
        migrations.CreateModel(
            name='CommunityEventRSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, max_length=255, verbose_name='Event ID')),
                ('event_title', models.CharField(blank=True, max_length=255, verbose_name='Event Title')),
                ('member_email', models.EmailField(db_index=True, max_length=254, verbose_name='Member Email')),
                ('member_name', models.CharField(max_length=150, verbose_name='Member Name')),
                ('status', models.CharField(choices=[('going', 'Going / Asistiré'), ('maybe', 'Maybe / Tal vez'), ('declined', 'Not Going / No podré')], default='going', max_length=20, verbose_name='RSVP Status')),
                ('notes', models.TextField(blank=True, verbose_name='Notes / Guests / Comments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event RSVP',
                'verbose_name_plural': 'Event RSVPs',
                'ordering': ['-updated_at'],
                'unique_together': {('event_id', 'member_email')},
            },
        ),
    ]
