# Generated by Django 6.1 on 2026-08-18 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0006_communityeventbroadcast_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Event Title')),
                ('category', models.CharField(choices=[('Cultural & Heritage', 'Cultural & Heritage'), ('Networking & Tech', 'Networking & Tech'), ('Family & Outdoors', 'Family & Outdoors'), ('Culinary & Social', 'Culinary & Social'), ('Community Gathering', 'Community Gathering')], default='Community Gathering', max_length=50, verbose_name='Category')),
                ('start_datetime', models.DateTimeField(verbose_name='Start Date & Time')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='End Date & Time')),
                ('location', models.CharField(default='San Francisco Bay Area', max_length=255, verbose_name='Location / Venue')),
                ('location_url', models.URLField(blank=True, verbose_name='Google Maps or Location URL')),
                ('description', models.TextField(blank=True, verbose_name='Description / Details')),
                ('created_by_name', models.CharField(blank=True, max_length=150, verbose_name='Created By (Name)')),
                ('created_by_email', models.EmailField(blank=True, max_length=254, verbose_name='Created By (Email)')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Community Event',
                'verbose_name_plural': 'Community Events',
                'ordering': ['start_datetime'],
            },
        ),
        migrations.AlterField(
            model_name='membershipauditlog',
            name='action',
            field=models.CharField(choices=[('submitted', 'Request Submitted'), ('approved', 'Request Approved'), ('rejected', 'Request Rejected'), ('direct_added', 'Member Added Directly'), ('deleted', 'Member Deleted'), ('survey_created', 'Survey Created'), ('survey_closed', 'Survey Closed/Reopened'), ('survey_deleted', 'Survey Deleted'), ('event_broadcast', 'Event Notification Broadcast'), ('event_created', 'Event Created'), ('event_updated', 'Event Updated'), ('event_deleted', 'Event Deleted')], db_index=True, max_length=30, verbose_name='Action'),
        ),
    ]
