# Generated by Django 6.1 on 2026-08-18 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0007_communityevent_alter_membershipauditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='email_notifications',
            field=models.BooleanField(default=True, help_text='Opt in or out of community event broadcasts and updates via email.', verbose_name='Receive Email Notifications'),
        ),
    ]
