# Generated by Django 6.1 on 2026-08-19 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0008_memberprofile_email_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipauditlog',
            name='action',
            field=models.CharField(choices=[('submitted', 'Request Submitted'), ('approved', 'Request Approved'), ('rejected', 'Request Rejected'), ('direct_added', 'Member Added Directly'), ('deleted', 'Member Deleted'), ('survey_created', 'Survey Created'), ('survey_closed', 'Survey Closed/Reopened'), ('survey_deleted', 'Survey Deleted'), ('event_broadcast', 'Event Notification Broadcast'), ('event_created', 'Event Created'), ('event_updated', 'Event Updated'), ('event_deleted', 'Event Deleted'), ('recommendation_created', 'Recommendation Created')], db_index=True, max_length=30, verbose_name='Action'),
        ),
    ]
