# Generated by Django 6.1 on 2026-09-01 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0010_alter_membershipauditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityevent',
            name='category',
            field=models.CharField(choices=[('Cultural & Heritage', 'Cultural & Heritage'), ('Networking & Tech', 'Networking & Tech'), ('Family & Outdoors', 'Family & Outdoors'), ('Culinary & Social', 'Culinary & Social'), ('Community Gathering', 'Community Gathering'), ('Salidas solo mamis', 'Salidas solo mamis'), ('Salidas solo papis', 'Salidas solo papis')], default='Community Gathering', max_length=50, verbose_name='Category'),
        ),
    ]
