# Generated by Django 6.1 on 2026-09-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0012_alter_membershipauditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityeventrsvp',
            name='adults_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Number of Adults'),
        ),
        migrations.AddField(
            model_name='communityeventrsvp',
            name='contribution',
            field=models.CharField(blank=True, max_length=255, verbose_name='Contribution (Things I am bringing)'),
        ),
        migrations.AddField(
            model_name='communityeventrsvp',
            name='kids_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of Kids'),
        ),
    ]
