# Generated by Django 6.1 on 2026-09-25 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0013_communityeventrsvp_adults_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityeventrsvp',
            name='kids_0_2',
            field=models.PositiveIntegerField(default=0, verbose_name='Kids (0 <= 2 years)'),
        ),
        migrations.AddField(
            model_name='communityeventrsvp',
            name='kids_10_plus',
            field=models.PositiveIntegerField(default=0, verbose_name='Kids (10+ years)'),
        ),
        migrations.AddField(
            model_name='communityeventrsvp',
            name='kids_2_5',
            field=models.PositiveIntegerField(default=0, verbose_name='Kids (2 <= 5 years)'),
        ),
        migrations.AddField(
            model_name='communityeventrsvp',
            name='kids_5_10',
            field=models.PositiveIntegerField(default=0, verbose_name='Kids (5 < 10 years)'),
        ),
        migrations.AlterField(
            model_name='communityeventrsvp',
            name='kids_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Kids'),
        ),
    ]
